# Token Data Informations:
# DON'T CHANGE THIS IF YOU DON'T KNOW WHAT ARE YOU DOING
# if you want change data in this token please do it in
# "Token Configuration" and reload plugin after that this
# selection is updating of new calculation counting data from
# Token Configuration:
Token price: 100.0 # BTC price = TokenCapitalization/AllTokens
Tokens left: 10.0 # If you want add new tokens to circulation
# I recommend add this for command /crypto [token] add [calculation] [amount]
# if you change this value in this tab Value [Token all tokens] in
# "Token configuration" is not automatic change.
# -----------------------------------------------------

# Token Configuration:
Token Name: "BTC"
Token all tokens: 10.0
Token Capitalization: 1000.0
Token Buy Tax: 1.0 #in %
Token Sell Tax: 1.0 #in %
# please add tax to token because if you set tax to 0, players has
# copy and get free tokens for manipulating small numbers after ","







# Admin Permissions:
BypassAllAdminCommand: "crypto.admin.*"
CommandCryptoAdminReload: "crypto.admin.reload"
CommandCryptoAdminAdd: "crypto.admin.add"
CommandCryptoAdminGive: "crypto.admin.give"
CommandCryptoAdminSubtract: "crypto.admin.subtract"
CommandCryptoAdminTake: "crypto.admin.take"
# Player Permissions:
RequirePlayerCommandsPermissions: false
CommandCryptoBuy: "crypto.buy"
CommandCryptoGet: "crypto.get"
CommandCryptoSell: "crypto.get"

# Debug mode - for founding bugs
DebugMode: false