name: CryptoMarket
version: '1.0-BETA'
main: com.aphonix.cryptoMarket.Main
api-version: '1.21'
authors: [ aphonix ]
description: Simulate Crypto Market Inside Your Server
depend: [Vault]
commands:
  crypto:
    description: Crypto Command
    usage: /crypto help